name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./Xam.HelpTools.Demo/Xam.HelpTools.Demo.csproj -c Release
    - name: Push_Nugets
      run: dotnet nuget push ./Xam.HelpTools.Demo/Artifacts/*nupkg --api-key oy2ntp7rbxlpazclos4ap5kqpirulniulbwjmw233n2p34 --source https://api.nuget.org/v3/index.json
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
