name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
#     - name: Build
#       run: dotnet pack ./Xam.HelpTools/Xam.HelpTools.csproj -c Release
    - name: Build package
      run: msbuild ./Xam.HelpTools/Xam.HelpTools.csproj -t:pack /property:Configuration=Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: packages
        path: ./**/Artifacts/*nupkg
#     - name: Push_Nugets
#       run: dotnet nuget push ./Xam.HelpTools/Artifacts/*nupkg --api-key ${{ secrets.API_NUGET_KEY }} --source https://api.nuget.org/v3/index.json
    #- name: Publish_artifcats
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
