# This is a basic workflow to help you get started with Actions

name: Release_toNuget

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  page_build:
    release:
      types: # This configuration does not affect the page_build event above
        - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download artifact
        uses: aochmann/actions-download-artifact@1.0.4
        with: 
          name: packages
      
      - name: Nuget push
        uses: EasyDesk/action-nuget-push@v1.0.0
        with:
          nuget_api_key: ${{ secrets.API_NUGET_KEY }}
          publish-dir: ./Artifacts

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
